### ISSUE TITLE
[Feature] Add option to select the language of the exported text data

### ISSUE THREAD

**Issue by Hiroa** [Rietty/AutoMammet#1]
Really usefull plugin, but by default, the export language is the one of the game (or dalamud ?).
Could you add an option to set the language for the text format ?

**Comment by Rietty** [comment]
I will look into it and check what I can do about setting the language option.

**Comment by Rietty** [comment]
Yes, so I went and checked and by default the exported language is the one in the game itself. I will figure out a way to make this be selectable by language. It also highlighted an interesting small bug I need to fix. Thanks!

The language selector will take a while because it's both not a high priority for me at the moment, and requires stuff to figure out.

**Comment by Rietty** [comment]
Looking into it a bit more and there doesn't seem to be an easy way to get the exported language changed, since this plugin is essentially pulling from the game's memory/info, there is nothing about language Y if you load game in language X. Thus from what I can tell you'll need to be on the language you want to export on. However I might be able to make a makeshift/hacky way to do it using a basic lookup table type thing. However I make no promises and will most likely not be doing it for a little while.

**Comment by Hiroa** [comment]
I don't know if you explore this path. Locally I change the language of the loaded ExcelSheet like this
`var addon = Dalamud.GameData.GetExcelSheet<Addon>(ClientLanguage.English)!;` on AutoMammet\Reader.cs:33
I didn't make extensive tests (I'm pretty good to break things), but my exports are now on english

![image](https://user-images.githubusercontent.com/3938368/190082543-55ecd809-f79b-4945-86f2-050e0905910c.png)

**Comment by Rietty** [comment]
Yes I found that too. :) Doing a bit more with it to make it nicer/easier to use with language switching but it does work now. Just need some tests before I push it to this branch.

**Comment by Rietty** [comment]
Added in commit: https://github.com/Rietty/AutoMammet/commit/26b843e78f19284513b38ebfd5035db9205066ed
